eno=int(input("Enter Employee Number: "))
ename=input("Enter Employee Name: ")
esal=float(input("Enter Employee Salary: "))
eaddr=input("Enter Employee Address: ")
married=bool(input("Enter Employee Marriage Status:[True|False]"))
print("Please confirm Information...")
print("Employee Number:",eno)
print("Employee Name:",ename)
print("Employee Salary:",esal)
print("Employee Address:",eaddr)
print("Employee Married ?:",married)

